version: '3'
services:
  eureka:
    build: ./eureka-discovery
    image: eureka:1.0
    restart: always
    ports:
      - "8761:8761"
  balancer:
    build: ./balancer
    image: balancer:1.0
    restart: always
    ports:
      - "9000:9000"
  ocr-parser:
    build: ./ocr-parser
    image: ocr-parser:1.0
    restart: always
    ports:
      - "8000"
  client:
    build: ./client
    image: client:1.0
    restart: always
    ports:
      - "4200:80"
