spring:
  application:
    name: balancer

discovery:
  url: http://eureka:8761

client:
  name: ocr-parser

allowedOrigin: http://localhost:4200/

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:${discovery.url}/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    com:
      netflix:
        discovery: off
