server:
  port: 8000

spring:
  application:
    name: ocr-parser

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    com:
      netflix:
        discovery: off
